### ISSUE TITLE
International stuck on "Updating..."

### ISSUE THREAD

**Issue by BarRaider** [tarikguney/weather-plugin-for-elgato-streamdeck#1]
Doesn't seem to be doing anything if I don't put a zipcode
But countries like UK don't have a numeric zipcode.
If I put "0" it just stays on "Updating" forever.

**Comment by tarikguney** [comment]
Have you tried with a postal code? Well... it still won't work as it always expects a numeric value for the zip code field. I will look into that. Thanks for the report.

**Comment by tarikguney** [comment]
Let me know if this helps! A new version with an improved international support has been released today https://github.com/tarikguney/weather-plugin-for-elgato-streamdeck/releases/tag/v2.0
