### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by max-arturo** [tarikguney/weather-plugin-for-elgato-streamdeck#2]
Good day.
Tell me please. Is it possible to display the temperature not in Fahrenheit, but in Celsius?

**Comment by tarikguney** [comment]
Sure, I can do that. All it takes is to apply a conversion math formula to convert F to C. I will add that to the next release.

**Comment by max-arturo** [comment]
OK. Thanks a lot.Will wait :)
And one more question. Accuweather [supports localization](https://developer.accuweather.com/localizations-by-language).
Is it possible to add a localization choice to the plugin? To show the weather in the desired language.

**Comment by tarikguney** [comment]
I am not sure about localization but the C and F degree support will come out in the next minor version. Today, I have a new major version with an improved international support. https://github.com/tarikguney/weather-plugin-for-elgato-streamdeck/releases/tag/v2.0

**Comment by tarikguney** [comment]
@max-arturo Hey, check this new version out! 

https://github.com/tarikguney/weather-plugin-for-elgato-streamdeck/releases/tag/v2.2

This release has new the Celsius selection.
