### ISSUE TITLE
version 2.2 not pulling info until manually clicking

### ISSUE THREAD

**Issue by mendyz** [tarikguney/weather-plugin-for-elgato-streamdeck#3]
version 2.2 not pulling info until manually clicking
weather username and api key made, data pulls just fine, icons display weather based. F degrees set. Well under the 50 free per day, I just installed it today.
I have multiple buttons on the same streamdeck, at different spots on the same page, for different cities.
one USA based, one International Based icon made.
Issue:  
When I click into my weather and clock page which I created on my streamdeck to show multiple cities clocks and weather data (It is not the main page). The icons made from your weather app version 2.2. just have your weather icon with the sun and cloud and blue circle on them instead of pulling the individual cities weather data.
They do update when clicked, but that mildly defeats the purpose and I would love them to auto pull as soon as I open that streamdeck canvas.
Did I do something wrong in setting them up?

**Comment by tarikguney** [comment]
Confirmed, it is a bug I have known for a while. I didn't care much but if others are using it and care about it, I will fix it. Thanks for reporting the issue.

**Comment by tarikguney** [comment]
A new version has been published which fixes the issue you ran into. 

https://github.com/tarikguney/weather-plugin-for-elgato-streamdeck/releases/tag/v2.3

Closing this.
