### ISSUE TITLE
the weather is not updated

### ISSUE THREAD

**Issue by ivannachkov** [tarikguney/weather-plugin-for-elgato-streamdeck#4]
Hi team,
I followed your guide however the plugin is not working. I see a message on the weather button - "...ted token H...". Unfortunately, I can't see the whole message so it's unclear to me what is the problem. I checked the Elgato logs but no info there. Could you suggest what might be the problem?

Regards

**Comment by tarikguney** [comment]
Hello, 

It is really hard to say much from this much information, and sorry for the trouble. However, your token might have expired, you may be using invalid token, or you exceeded your token daily limit by refreshing so many times a day. Let me know if you still get this problem.
