### ISSUE TITLE
Suggestion and request

### ISSUE THREAD

**Issue by GraXXoR** [tarikguney/weather-plugin-for-elgato-streamdeck#6]
Please update the instructions to add NOT to type a Title in the Title box rather than stating "no effect". Having text in this field prevents the app from displaying the weather thus completely breaking the App! 

It took me a good while to realise that me typing the word "AccuWeather" as the title was the reason why only "AccuWeather" was shown despite following the instructions. LOL.

REQUEST: Is it possible to make a dynamic icon reflecting the weather?

**Comment by tarikguney** [comment]
Thanks for the suggestion. The icon is supposed to be reflecting the weather, but there could be a bug that prevents it.
