### ISSUE TITLE
Option to display (or not) the text

### ISSUE THREAD

**Issue by kboyerTeacher** [tarikguney/weather-plugin-for-elgato-streamdeck#7]
Would be nice to add check box to activate or deactivate what is displayed as text. For exemple
[ ] Weather Condition
[ ] Temperature

I would like to only display the temperature as the weather condition is already showed by the icon and I think there is too much text so it's difficult to read.

Thanks
Kevin

**Comment by tarikguney** [comment]
Thanks for the suggestion!
